---
title: "Untitled"
output: html_document
---

```{r}
library(pacman)
p_load(tidyverse, brms, parallel, bayesplot)
ncores = detectCores()
setwd("C:/Users/95/Dropbox/MastersSem1/DecisionMaking/examCode")

```

### Manual approach: 
setting up function which can generate data. 
still lacking uncertainty. 

```{r}

## Gonzalez / Wu 
gonzWu <- function(delta, gamma, p){
  w = (delta * (p ** gamma)) / (delta * (p ** gamma) + (1-p)**gamma)
  #return(w)
}


```


```{r}
# create df: 

df = data.frame(#w = rep(1, participants*values_p),
                p = rep(c(0.01, 0.05, 0.15, 0.25, 0.5, 0.75, 0.85, 0.95, 0.99),
                        participants*items),
                ID = rep(1:participants, each = values_p*items),
                gamma = rep(rnorm(participants, .44, 0.01), 
                            each = values_p*items),
                delta = rep(rnorm(participants, .77, 0.01), 
                            each = values_p*items),
                items = rep(1:items, each = participants*values_p))

```

```{r}

genDF <- function(items, participants, values_p, 
                  delta, delta_SD, gamma, gamma_SD){
  
  # create df: 
  df = data.frame(#w = rep(1, participants*values_p),
                p = rep(c(0.01, 0.05, 0.15, 
                          0.25, 0.5, 0.75, 0.85, 0.95, 0.99),
                        participants*items),
                ID = rep(1:participants, each = values_p*items),
                gamma = rep(rnorm(items, gamma, gamma_SD), 
                            each = values_p*participants),
                delta = rep(rnorm(participants, delta, delta_SD), 
                            each = values_p*items),
                items = rep(1:items, each = participants*values_p))
  
  return(df)
}

```

```{r}
# generate DF: 

df <- genDF(items = 10, participants = 100, values_p = 9,
               delta = 0.77, delta_SD = 0.1, 
               gamma = 0.44, gamma_SD = 0.1)

```


```{r}

# compute W in this silly manner: 
dfW <- df %>%
  mutate(w = gonzWu(delta, gamma, p))

# write csv 
write_csv(dfW, "sample_data.csv")

```

Saved just in case:

```{r}

est_param <- function(fun, num_a, num_p) {
  
  a = seq(0, 1, by = num_a)
  p = seq(0, 1, by = num_p)
  
  df <- tibble(affect = numeric(),
               probability = numeric(),
               utility = numeric()) 
  
  for(aff in a){
    value = sapply(p, fun, a = aff)
    df = rbind(df, 
               tibble(affect = rep(aff, length(p)), 
                      probability = p, 
                      utility = value))
  }
  
  return(df)
}
```




