---
title: "Untitled"
output: html_document
---

Inspiration:
https://sahirbhatnagar.com/bayesian-stan
https://tysonbarrett.com/jekyll/update/2019/07/21/BayesianSims/

packages 

```{r}
library(pacman)
p_load(tidyverse, parallel, brms)
ncores = detectCores()
setwd("C:/Users/95/BayesianDecisionWeights/Code")
```

read simulated data 

```{r}

df <- read_csv("../Data/exp2_sim_data.csv") %>%
  rename(p = probability,
         gammaT = gamma_true,
         deltaT = delta_true,
         gammaO = gamma_obs, 
         deltaO = delta_obs, 
         w = w_prob)

```

Try to fit it to just ONE item

```{r}

df_item1 <- df %>%
  filter(item == 1,
         w >= 0 & w <= 1) %>%
  select(c(ID, p, w)) 
  
```

```{r}

(prior <- brms::get_prior(
  brms::bf(w ~ (deltaO * (p ** gammaO)) / 
                      (deltaO * (p ** gammaO) +
                         (1-p)**gammaO), 
               gammaO ~ 1,
               deltaO ~ 1,
               nl = TRUE),
  data = df_item1, 
  family = gaussian()))

```

why does it set both?

```{r}

prior
prior$prior[2] <- "normal(0.7, 0.2)"
prior$prior[4] <- "normal(0.2, 0.2)"
prior

```

```{r}

newMod <- brms::brm(
  bf(w ~ (deltaO * (p ** gammaO)) / 
       (deltaO * (p **gammaO) +
          (1-p)**gammaO),
     gammaO ~ 1,
     deltaO ~ 1,
     nl = TRUE),
  data = df_item1, 
  prior = prior,
  chains = 6,
  iter = 10000,
  cores = 6,
  control = list(adapt_delta = 0.9)) ## does not want to overwrite.

```

```{r}
(res <- summary(newMod))
plot(newMod)
```

### for several ITEMS

```{r}
(prior <- brms::get_prior(
  brms::bf(w ~ (deltaO * (p ** gammaO)) / 
                      (deltaO * (p ** gammaO) +
                         (1-p)**gammaO), 
               gammaO ~ 0 + Intercept + item,
               deltaO ~ 0 + Intercept + item,
               nl = TRUE),
  data = df, 
  family = gaussian()))


```

set priors: 
https://sahirbhatnagar.com/bayesian-stan

```{r}
prior
prior$prior[c(6,7)] <- "normal(0, 0.2)"
prior$prior[3] <- "normal(0.7, 0.2)"
prior$prior[4] <- "normal(0, 0.2)"
prior
##
priors <- prior(normal(0.7, 0.2), 
                class = "b",
                coef = "Intercept",
                nlpar = "deltaO") +
  prior(normal(0, 0.2),
        class = "b",
        coef = "item",
        nlpar = "deltaO") +
  prior(normal(0.2, 0.2),
        class = "b",
        coef = "Intercept",
        nlpar = "gammaO") +
  prior(normal(0.2, 0.2), 
        class = "b",
        coef = "item",
        nlpar = "gammaO")

```

```{r}

```

