---
title: "Untitled"
output: html_document
---

packages 

```{r}
library(pacman)
p_load(tidyverse, parallel, brms)
ncores = detectCores()
setwd("C:/Users/95/BayesianDecisionWeights/Code")
```

read simulated data 

```{r}

df <- read_csv("sample_data.csv") %>%
  select(-c(delta, gamma)) %>%
  filter(items == 1 | items == 2)

```

get priors 

```{r}

(prior <- brms::get_prior(
  brms::bf(w ~ (delta * (p ** gamma)) / 
                      (delta * (p ** gamma) + (1-p)**gamma), 
               gamma ~ 1 + items + (1|ID),
               delta ~ 1,
               nl = TRUE),
  data = df, 
  family = gaussian()))


```


set priors: 

```{r}

prior1 <- prior(normal(0.44, 0.2), nlpar = "gamma") +
  prior(normal(0.77, 0.2), nlpar = "delta")

```

define model:
1. is the formula correct?
2. are the priors right?

# this takes a long time.. 

```{r}

randomMod <- brm(bf(w ~ (delta * (p ** gamma)) / 
                      (delta * (p **gamma) + (1-p)**gamma), 
               gamma ~ 1 + items + (1|ID),
               delta ~ 1 + items + (1|ID),
               nl = TRUE),
            data = df, prior = prior1,
            iter = 2000,
            cores = ncores,
            file = "IDintercept") 

```


