---
title: "Untitled"
output: html_document
---

https://sahirbhatnagar.com/bayesian-stan

```{r}
library(pacman)
p_load(tidyverse, parallel, brms)
ncores = detectCores()
setwd("C:/Users/95/BayesianDecisionWeights/Code")
```

```{r}
rm(list=ls())

# number of subjects
n = 500

# number of time points
t = 2

# SNR
SNR = 2

# true coefficient value
b <- 3

# simulate independent covariates
A <- rgamma(n*t, shape = 3)
B <- rnorm(n*t)

# random effect: same for time 1 and time 2
random_eff <- rpois(n, lambda = 10)

y.star <- b * A + b^2 * B + rep(random_eff,2)
error <- rnorm(n*t)
k <- sqrt(stats::var(y.star)/(SNR*stats::var(error)))

# response
yij <- y.star + k*error 

dat1 <- data.frame(yij, 
                   aij = A, 
                   bij = B, 
                   ID = rep(1:n, times = 2))
```

```{r}
(prior <- brms::get_prior(
  brms::bf(yij ~ beta * aij + (beta^2) * bij + mui, 
           mui ~ 1 + (1|ID),
           beta ~ 1, 
           nl = TRUE),
  data = dat1, 
  family = gaussian()))
```

here it goes awry..?

```{r}
prior$prior[c(2,4)] <- "normal(0,10)"
prior$prior[8] <- "student_t(3, 0, 11)"
prior
```

```{r}
# refresh = 0 to surpress output
fit1 <- brms::brm(
  bf(yij ~ beta * aij + (beta^2) * bij + mui, 
     mui ~ 1 + (1|ID),
     beta ~ 1, 
     nl = TRUE),
  data = dat1, 
  family = gaussian(),
  prior = prior,
  control = list(adapt_delta = 0.9),
  iter = 10000, 
  thin = 2, 
  chains = 6, 
  cores = 6, 
  refresh = 0)
```

