---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

load packages

```{r}

library(pacman)
p_load(tidyverse)

```

function for computing Rottenstreich & Wu/Gonzales

```{r}

## rottenstreich
rottenstreich <- function(a, p){
  w = p**(1-a) / (p**(1-a) + (1-p)**(1-a))
  #return(w)
}

## wu
wu <- function(a, p){
  w = (p**a / (p**a + (1-p)**a)**(1-a))
}

```

function for estimating params with these functions

```{r}
## use the functions:

est_param <- function(fun, num_a, num_p) {
  
  a = seq(0, 1, by = num_a)
  p = seq(0, 1, by = num_p)
  
  df <- tibble(affect = numeric(),
               probability = numeric(),
               utility = numeric()) 
  
  for(aff in a){
    value = sapply(p, fun, a = aff)
    df = rbind(df, 
               tibble(affect = rep(aff, length(p)), 
                      probability = p, 
                      utility = value))
  }
  
  return(df)
}
  
```

Get the data 

```{r}

rot <- est_param(rottenstreich, 0.1, 0.01)
wuGon <- est_param(rottenstreich, 0.1, 0.01)

```

Function for plotting

```{r}

plotW <- function(df, x, y, group){
  ggplot(df, aes({{x}}, {{y}}, group = {{group}}, color = {{group}})) +
    geom_line()
}

```

Use the plotting function

```{r}

## they are the same.. (it seems): prove it.
plotW(rot, probability, utility, affect)
plotW(wuGon, probability, utility, affect)
```


