---
title: "param_est"
output: html_document
---


https://cran.r-project.org/web/packages/brms/vignettes/brms_nonlinear.html

```{r}
library(pacman)
p_load(tidyverse, brms)
```


```{r}
b <- c(2, 0.75)
x <- rnorm(100)
y <- rnorm(100, mean = b[1] * exp(b[2] * x))
dat1 <- data.frame(x, y)
```

```{r}
prior1 <- prior(normal(1, 2), nlpar = "b1") +
  prior(normal(0, 2), nlpar = "b2")

fit1 <- brm(bf(y ~ b1 * exp(b2 * x), b1 + b2 ~ 1, nl = TRUE),
            data = dat1, prior = prior1)

```

```{r}
summary(fit1)
```

```{r}
plot(fit1)
```

```{r}
plot(conditional_effects(fit1), points = TRUE)
```

```{r}
data(loss)
head(loss)
```

non-linear BRMS model,
why does only ULT have random effect?
estimating effect of year ON that parameter. 

```{r}
fit_loss <- brm(
  bf(cum ~ ult * (1 - exp(-(dev/theta)^omega)),
     ult ~ 1 + (1|AY), omega ~ 1, theta ~ 1, 
     nl = TRUE),
  data = loss, family = gaussian(),
  prior = c(
    prior(normal(5000, 1000), nlpar = "ult"),
    prior(normal(1, 2), nlpar = "omega"),
    prior(normal(45, 10), nlpar = "theta")
  ),
  control = list(adapt_delta = 0.9)
)

summary(fit_loss)
```

predicted values: 

```{r}

conditions <- data.frame(AY = unique(loss$AY))
rownames(conditions) <- unique(loss$AY)
me_loss <- conditional_effects(
  fit_loss, conditions = conditions, 
  re_formula = NULL, method = "predict"
)
plot(me_loss, ncol = 5, points = TRUE)

```
